### ISSUE TITLE
panel file

### ISSUE THREAD

**Issue by sputtering** [wntrblm/Helium#2]
According to the Licence file, it seems to indicate that under the _hardware_ folder should be a panel folder (or file). I was not able to find the panel file there, nor anywhere in the repository. Am I not looking in the right area?

Just for context, in the future, I was going to get a Helium kit to assemble, and then make my own custom panel to use.

**Comment by theacodes** [comment]
@sputtering I have no idea how I missed this for so long, my apologies

The faceplate files have been added, but even better, I've added a full [self sourcing guide](https://helium.wntr.dev/self-source-build/) and you can also buy bare PCBs and faceplates from [us](https://winterbloom.com/shop/helium-boards)

💜
